### PR TITLE
Tidy up the parens to match the project style

### PR DESCRIPTION
**Pull request by alexwlchan**

### CODE REVIEW

**Comment by alexwlchan** [comment]
Just FYI (because we were chatting about this last week), I don't have the ability to merge pull requests:

canimerge

**Comment by Lukasa** [comment]
That's perplexing, because as you can see, contributors have write access:

screen shot 2016-09-23 at 11 52 01

**Comment by Lukasa** [comment]
Might have to find someone who understands github permissions better than I do to work out what's going on.

**Comment by alexwlchan** [comment]
I'd guess that maybe it's something to do with master being a protected branch -- I can push to other branches, just not to master.

**Comment by Lukasa** [comment]
Good guess! Now you are free!

**Pull request merged**
