### PR TITLE
Add basic Tornado example

### LINKED ISSUE #12: Tornado example implementation
Why leave Tornado out of the fun of example implementations?

### PR DESCRIPTION
**Pull request by toffer**
This basic example follows the `eventlet` example, and simply echoes back a JSON representation of the request headers.

I copied the SSL certs from the Twisted example, since they are still current.

Resolves #12.

### CODE REVIEW

**Comment by Lukasa** [comment]
Cool, thanks @toffer! Are you interested in adding the example to the docs as well? (See `docs/source/eventlet-example.rst` and `docs/source/examples.rst` for guidance on what you'd need to do.)

Let me know if you're not, and I can do it myself. =)

**Comment by toffer** [comment]
@Lukasa Of course! I'd be happy to add the example to the docs. Sorry I overlooked that.

**Comment by Lukasa** [comment]
No need to apologise!

**Comment by toffer** [comment]
@Lukasa While adding to the docs, I also took the liberty of adding myself to the contributors list.

Please let me know if you need anything else!

**Comment by Lukasa** [comment]
Fantastic, thanks so much @toffer! :sparkles: :cake: :sparkles:

**Comment by Lukasa** [comment]
Per our [one of the team](http://python-hyper.org/en/latest/one-of-the-team.html) policy, you'll find an invite to the Python Hyper organisation in your inbox. Welcome on board!

**Pull request merged**
