### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by Lukasa**

### CODE REVIEW

**Comment by rbtcollins** [comment]
So since this is automated, should we just hit merge?

**Comment by rbtcollins** [comment]
Oh... I can't hit merge, nvm :)

**Comment by Lukasa** [comment]
@rbtcollins You should have been able to merge this if it passes tests. Were they passing?

**Comment by sigmavirus24** [comment]
@Lukasa they were

**Comment by rbtcollins** [comment]
I could 'Close Pull Request' or 'Comment', but not 'Merge'. Merge is
apparently restricted to folk with write access.

**Comment by Lukasa** [comment]
@rbtcollins You should have write access, but let me double check.

**Pull request merged**
