### PR TITLE
Remove deprecated stuff: round one.

### PR DESCRIPTION
**Pull request by Lukasa**
This is an initial removal of the deprecated code within hyper-h2. There is one more change we'd like to make: we'd like to make the default representation of headers bytes, not unicode. That will come along in a separate PR.

### CODE REVIEW

**Comment by Lukasa** [comment]
And rightly so. ;)

**Comment by Lukasa** [comment]
So, the twisted master failures are unfortunate. Naturally, twisted master fails because this is a breaking change. However, they pin out our new breaking version. Not sure what to do about that: should we temporarily move it to "allowed failures"?

**Comment by alexwlchan** [comment]
> So, the twisted master failures are unfortunate. Naturally, twisted master fails because this is a breaking change. However, they pin out our new breaking version. Not sure what to do about that: should we temporarily move it to "allowed failures"?

That feels a bit icky – especially as the whole point of this change is to fix things for twisted, it would be good to have some guarantee of that before releasing 3.0 and claiming it’s fixed.

I notice that our tox.ini [installs twisted from a GitHub repo](https://github.com/python-hyper/hyper-h2/blob/master/tox.ini#L19), not PyPI. We could fork twisted, bump the h2 version requirement in the fork and point tox at the fork – that allows us to check everything works correctly with our changes. Then when the version gets bumped in twisted master, we revert the tox change.

I haven’t had enough sleep to know if that’s a brilliant or a terrible idea.

**Comment by alexwlchan** [comment]
Alternatively, it looks like the vast majority of twisted errors come from one line, where it uses deprecated parameters that’s being removed by this patch: https://github.com/twisted/twisted/blob/trunk/src/twisted/web/_http2.py#L125

We could just fix this on the twisted side to use `H2Configuration`?

**Comment by alexwlchan** [comment]
I’ve opened https://github.com/twisted/twisted/pull/750 to fix this behaviour on twisted master. Once that’s merged, we should be able to re-run the twisted tests and (hopefully!) get a pass.

**Comment by Lukasa** [comment]
Cool, good idea. Handily, I'm a Twisted committer, so we can get this through pretty nicely. :grin:

**Comment by Lukasa** [comment]
Ok let's rebuild these.

**Comment by Lukasa** [comment]
Looks like there are some other problems in that Twisted code too. ;) @alexwlchan, are you interested in making a follow-up patch to Twisted? If not, I'll do it.

**Comment by alexwlchan** [comment]
> Looks like there are some other problems in that Twisted code too. ;) @alexwlchan, are you interested in making a follow-up patch to Twisted?

Yep, I’ll do it later.

**Comment by alexwlchan** [comment]
See https://twistedmatrix.com/trac/ticket/9092#ticket

**Comment by alexwlchan** [comment]
See https://github.com/twisted/twisted/pull/751 for what I think is the remaining twisted deprecations.

**Comment by alexwlchan** [comment]
Okay, I’ve kicked off another round of twisted tests.

**Comment by Lukasa** [comment]
🍿

**Comment by Lukasa** [comment]
Looks like some stuff got missed. :smile:

**Comment by Lukasa** [comment]
Hurrah, looks good! Thanks for the work today @alexwlchan. :sparkles:

**Pull request merged**
