### PR TITLE
Allow zero-length header list in SETTINGS_MAX_HEADER_LIST_SIZE

### LINKED ISSUE #422: Website fails with InvalidSettingsValueError: Setting 6 has invalid value 0
Hi,

I cam across this website https://www.cam.ac.uk
If I try to fetch `/` via h2, I get this error:
`InvalidSettingsValueError: Setting 6 has invalid value 0`

However, curl & Chrome seem to have no problem in loading the website.

Minimal example to reproduce the error:
```python
#!/usr/bin/env python3

import certifi
import h2.connection
import h2.events

import errno
import socket
import ssl
import time

SERVER_NAME = 'www.cam.ac.uk'

socket.setdefaulttimeout(2)

c = h2.connection.H2Connection()
c.initiate_connection()

ctx = ssl.create_default_context(cafile=certifi.where())
ctx.set_alpn_protocols(['h2', 'http/1.1'])
ctx.set_npn_protocols(['h2', 'http/1.1'])

s = socket.create_connection((SERVER_NAME, 443))
s = ctx.wrap_socket(s, server_hostname=SERVER_NAME)

s.sendall(c.data_to_send())

headers = [
    (':method', 'GET'),
    (':path', '/'),
    (':authority', SERVER_NAME),
    (':scheme', 'https'),
]
c.send_headers(1, headers, end_stream=True)
s.sendall(c.data_to_send())

while True:
    data = s.recv(65536 * 256)
    if not data:
        break

    events = c.receive_data(data)
    s.sendall(c.data_to_send())

    for event in events:
        print(event)
```

### PR DESCRIPTION
**Pull request by alexwlchan**
Fixes #422.

### CODE REVIEW

**Comment by Kriechi** [comment]
Thanks for the fast fix!
@Lukasa any chance to get a really fast v2.5.1? 
We have a @mitmproxy release scheduled for today/tomorrow and it would be great to include this bugfix!

**Comment by Lukasa** [comment]
@Kriechi It's on my todo, I'll see if I can get to it sometime today.

**Comment by Lukasa** [comment]
And there we go, v2.5.1 is out the door. Happy Holidays @Kriechi, consider the fast v2.5.1 my gift to you. ;)

**Comment by Kriechi** [comment]
Cheers! 🎉 👍 👏 
Happy Holidays as well @Lukasa!

**Pull request merged**
