### PR TITLE
Fix link to Priority lib

### PR DESCRIPTION
**Pull request by drpoggi**
Not sure if the link is actually broken or if the documentation isn't building correctly, just thought I'd bring it your attention.

### CODE REVIEW

**Comment by alexwlchan** [comment]
I suspect the link is actually meant to be <http://python-hyper.org/priority/>, because `http://python-hyper/` isn’t a valid address.

**Comment by drpoggi** [comment]
Yup that would make more sense, updated.

**Comment by Lukasa** [comment]
Thanks for that catch! :cookie:

**Comment by Lukasa** [comment]
Thanks @drpoggi, [welcome to the team](http://python-hyper.org/en/latest/one-of-the-team.html)!

**Comment by drpoggi** [comment]
Thanks @Lukasa, I look forward to making more substantial contributions in the future!

**Comment by Lukasa** [comment]
We're looking forward to it too, @drpoggi. =D

**Pull request merged**
